name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your great evaluation in making up this issue for our repository. Kindly allow us some time, while code maintainers or reviewers see your addressed issue.'
        pr-message: 'Yay!!! You just made your first pull request in our InternshipPortal Repository. Thanks for taking time in doing so. Hope you like the project, would love to see more PRs from you. Please kindly wait for one of the reviewer to check out the code and its addressed bug or feature.'
